version: '3'
services:
  localstack:
    image: "localstack/localstack:0.10.5"
    ports:
      - "4574:4574"
      - "8080:8080"
    environment:
      - LAMBDA_EXECUTOR=docker
      - SERVICES=lambda
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: localstack