version: '3'
services:
  localstack:
    image: "localstack/localstack:0.10.5"
    ports:
      - "4572:4572"
      - "4574:4574"
      - "4583:4583"
      - "8080:8080"
    environment:
      - LAMBDA_EXECUTOR=docker
      - SERVICES=lambda,s3,ssm
      - AWS_ACCESS_KEY_ID=KEY
      - AWS_SECRET_ACCESS_KEY=SECRET
      - AWS_REGION=us-east-1
      - DEFAULT_REGION=us-east-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: localstack
  mountebank:
    image: andyrbell/mountebank
    ports:
      - "2525:2525"
      - "4545:4545"
    container_name: mountebank
  command:
    build:
      context: .
      dockerfile: dockerfile-command
    environment:
      - environment=ci
    container_name: command
    stdin_open: true
    tty: true
    ports:
      - "8082:8082"
    depends_on:
      - localstack
      - mountebank

   