AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to deploy pipeline-demo
Parameters:
  Environment:
    Description: Name of the AWS Environment the function is running in
    Type: String
    AllowedValues:
      - aws
      - dev
      - test
      - prod
  FunctionS3Bucket:
    Description: S3 Bucket where the lambda code is stored
    Type: String
    Default: murph-deployment
  FunctionS3Key:
    Description: S3 Key for the lambda file
    Type: String
Resources:
  QuoteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: murph-quote-bucket
      VersioningConfiguration:
        Status: Enabled
  QuoteFetchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: QuoteFetchPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
                  - s3:DeleteObjectVersion
                  - s3:GetObjectVersionTagging
                  - s3:ListBucket
                  - s3:GetObjectAcl
                  - s3:AbortMultipartUpload
                  - s3:GetObjectTagging
                  - s3:DeleteObject
                  - s3:ListBucketMultipartUploads
                  - s3:GetObjectRetention
                  - s3:ListMultipartUploadParts
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetBucketLocation
                  - s3:GetObjectVersion
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: QuoteBucket
                - "/*"
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref FunctionS3Bucket
        S3Key: !Ref FunctionS3Key
      Description: Pipeline-demo-lambda
      FunctionName: Pipeline-Demo
      Handler: "pipeline-demo-app::pipeline_demo_app.Function::FunctionHandler"
      MemorySize: 512
      Runtime: "dotnetcore2.1"
      Role: !GetAtt QuoteFetchRole.Arn
      Timeout: 60
      Environment:
        Variables:
          environment: !Ref Environment
